# Configuração do YAMLLint
# Documentação: https://yamllint.readthedocs.io/

extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: true

  comments:
    min-spaces-from-content: 1

  comments-indentation: {}

  document-start: disable  # Não requer --- no início

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

ignore: |
  .github/
  node_modules/
  venv/
  .venv/
