---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu-docker
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible
  playbooks:
    converge: ../../../docker.yml

verifier:
  name: ansible
