
---
  - name: "Install Google Chrome"
    hosts: localhost
    connection: local
    tasks:
      - name: Add a google Apt signing key
        ansible.builtin.apt_key:
          url: https://dl-ssl.google.com/linux/linux_signing_key.pub
          state: present

      - name: Add google repository into sources list
        ansible.builtin.apt_repository:
          repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
          state: present

      - name: Update apt cache
        apt: update_cache=yes

      - name: Install Google Chrome
        apt: pkg=google-chrome-stable state=present
