---
- import_playbook: desktop-minimal.yml
- import_playbook: docker.yml
- import_playbook: chrome.yml
- import_playbook: golang.yml
- import_playbook: java.yml
- import_playbook: ruby.yml
- import_playbook: emacs27.yml
- import_playbook: cursor.yml
- import_playbook: arduino-cli.yml
- import_playbook: genisoimage.yml
- import_playbook: datadog-ci.yml
- import_playbook: graphviz.yml
