---
  - name: "Setup Dotnet Core"
    hosts: localhost
    connection: localhost
    vars:
      dotnet_version: 5.0.300
    tasks:
      - name: "Clone asdf"
        git:
          repo: https://github.com/asdf-vm/asdf.git
          dest: '/home/pahagon/.asdf'
          version: v0.8.0

      - name: Add dotnet plugin to asdf [https://github.com/asdf-vm/asdf-dotnet-core]
        command: "asdf plugin-add dotnet-core"
        register: dotnet_add
        failed_when: dotnet_add == 2

      - name: Install dotnet {{dotnet_version}} with asdf
        command: asdf install dotnet-core {{dotnet_version}}

      - name: Set global version for dotnet to {{dotnet_version}}
        command: "asdf global dotnet-core {{dotnet_version}}"

