---
  - name: "Setup Node"
    hosts: localhost
    connection: localhost
    vars_files:
      - common_vars.yml
    vars:
      node_version: 20.12.0
    tasks:
      - include_tasks: common_tasks.yml

      - name: Add nodejs plugin to asdf [https://github.com/asdf-vm/asdf-nodejs]
        command: "asdf plugin-add nodejs"
        register: node_add
        failed_when: node_add == 2

      - name: Install nodejs {{node_version}} with asdf
        command: asdf install nodejs {{node_version}}

      - name: Set global version for nodejs to {{node_version}}
        command: "asdf global nodejs {{node_version}}"

      - name: Install "yarn" node.js package globally
        npm:
          name: yarn
          global: yes

      - name: Set npm init author name
        command: "npm config set init-author-name \"Paulo Ahagon\""

      - name: Set npm init author email
        command: "npm config set init-author-email pahagon@gmail.com"

      - name: Set npm init license
        command: "npm config set init-license MIT"

      - name: Set npm init version
        command: "npm config set init-version \"1.0.0\""


