---
  - name: "Setup Python"
    hosts: localhost
    connection: localhost
    vars_files:
      - common_vars.yml 
    vars:
      python_version: 3.12.2
    tasks:
      - include_tasks: common_tasks.yml

      - name: "Install the lastet version of dependencies"
        package:
          name:
            - build-essential
            - checkinstall
            - libncursesw5-dev
            - libssl-dev
            - libsqlite3-dev
            - tk-dev
            - libgdbm-dev
            - libc6-dev
            - libbz2-dev
        become: true

      - name: Add python plugin to asdf [https://github.com/asdf-vm/asdf-python]
        command: "asdf plugin-add python"
        register: python_add
        failed_when: python_add == 2

      - name: Install python {{python_version}} with asdf
        command: asdf install python {{python_version}}

